server.port=8080
spring.application.name=api-gateway

eureka.client.enabled=false

jwt.secret-key=OoZT8hVO0IOr7WZuU7beibI4wQ5cByYX!

# Auth service route (direct URL)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URI:http://auth-service:80}
spring.cloud.gateway.routes[0].predicates=Path=/auth/**
spring.cloud.gateway.routes[0].filters=StripPrefix=1

# User service route (direct URL)
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URI:http://user-service:80}
spring.cloud.gateway.routes[1].predicates=Path=/user/**
spring.cloud.gateway.routes[1].filters=StripPrefix=1

# Nse service route (direct URL)
spring.cloud.gateway.routes[2].id=nse-service
spring.cloud.gateway.routes[2].uri=${NSE_SERVICE_URI:http://nse-service:80}
spring.cloud.gateway.routes[2].predicates=Path=/nse/**
spring.cloud.gateway.routes[2].filters=StripPrefix=1

# Amfi service route (direct URL)
spring.cloud.gateway.routes[3].id=amfi-service
spring.cloud.gateway.routes[3].uri=${AMFI_SERVICE_URI:http://amfi-service:80}
spring.cloud.gateway.routes[3].predicates=Path=/amfi/**
spring.cloud.gateway.routes[3].filters=StripPrefix=1



# Swagger for auth
spring.cloud.gateway.routes[4].id=auth-swagger
spring.cloud.gateway.routes[4].uri=${AUTH_SERVICE_URI:http://auth-service:80}
spring.cloud.gateway.routes[4].predicates[0]=Path=/auth/v3/api-docs,/auth/swagger-ui.html,/auth/swagger-ui/**
spring.cloud.gateway.routes[4].filters=StripPrefix=1

# Swagger for user
spring.cloud.gateway.routes[5].id=user-swagger
spring.cloud.gateway.routes[5].uri=${USER_SERVICE_URI:http://user-service:80}
spring.cloud.gateway.routes[5].predicates[0]=Path=/user/v3/api-docs,/user/swagger-ui.html,/user/swagger-ui/**
spring.cloud.gateway.routes[5].filters=StripPrefix=1


# Swagger for nse
spring.cloud.gateway.routes[6].id=nse-swagger
spring.cloud.gateway.routes[6].uri=${NSE_SERVICE_URI:http://nse-service:80}
spring.cloud.gateway.routes[6].predicates[0]=Path=/nse/v3/api-docs,/nse/swagger-ui.html,/nse/swagger-ui/**
spring.cloud.gateway.routes[6].filters=StripPrefix=1

# Swagger for amfi
spring.cloud.gateway.routes[7].id=amfi-swagger
spring.cloud.gateway.routes[7].uri=${AMFI_SERVICE_URI:http://amfi-service:80}
spring.cloud.gateway.routes[7].predicates[0]=Path=/amfi/v3/api-docs,/amfi/swagger-ui.html,/amfi/swagger-ui/**
spring.cloud.gateway.routes[7].filters=StripPrefix=1



springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

springdoc.swagger-ui.urls[2].name=nse-service
springdoc.swagger-ui.urls[2].url=/nse/v3/api-docs

springdoc.swagger-ui.urls[3].name=amfi-service
springdoc.swagger-ui.urls[3].url=/amfi/v3/api-docs


springdoc.swagger-ui.path=/internal-api-docs

