server.port=8081
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

jwt.secret-key = OoZT8hVO0IOr7WZuU7beibI4wQ5cByYX!

# Swagger routes (more specific - should come first)
# Swagger: auth-service
spring.cloud.gateway.routes[0].id=auth-swagger
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/v3/api-docs,/auth/swagger-ui.html,/auth/swagger-ui/**
spring.cloud.gateway.routes[0].filters=StripPrefix=1

# Swagger: user-service
spring.cloud.gateway.routes[1].id=user-swagger
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/v3/api-docs,/user/swagger-ui.html,/user/swagger-ui/**
spring.cloud.gateway.routes[1].filters=StripPrefix=1

# Swagger: nse-service
spring.cloud.gateway.routes[2].id=nse-swagger
spring.cloud.gateway.routes[2].uri=lb://NSE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/nse/v3/api-docs,/nse/swagger-ui.html,/nse/swagger-ui/**
spring.cloud.gateway.routes[2].filters=StripPrefix=1

# Swagger: amfi-service
spring.cloud.gateway.routes[3].id=amfi-swagger
spring.cloud.gateway.routes[3].uri=lb://AMFI-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/amfi/v3/api-docs,/amfi/swagger-ui.html,/amfi/swagger-ui/**
spring.cloud.gateway.routes[3].filters=StripPrefix=1

# Swagger: bse-service
spring.cloud.gateway.routes[4].id=bse-swagger
spring.cloud.gateway.routes[4].uri=lb://BSE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/bse/v3/api-docs,/bse/swagger-ui.html,/bse/swagger-ui/**
spring.cloud.gateway.routes[4].filters=StripPrefix=1

# Swagger: aum-service
spring.cloud.gateway.routes[5].id=aum-swagger
spring.cloud.gateway.routes[5].uri=lb://AUM-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/aum/v3/api-docs,/aum/swagger-ui.html,/aum/swagger-ui/**
spring.cloud.gateway.routes[5].filters=StripPrefix=1


# Swagger: brokerage-service
spring.cloud.gateway.routes[6].id=brokerage-swagger
spring.cloud.gateway.routes[6].uri=lb://BROKERAGE-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/brokerage/v3/api-docs,/brokerage/swagger-ui.html,/brokerage/swagger-ui/**
spring.cloud.gateway.routes[6].filters=StripPrefix=1

# Main service routes (less specific - should come after Swagger routes)
# Auth service
spring.cloud.gateway.routes[7].id=auth-service
spring.cloud.gateway.routes[7].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[7].predicates=Path=/auth/**
spring.cloud.gateway.routes[7].filters=StripPrefix=1

# User service
spring.cloud.gateway.routes[8].id=user-service
spring.cloud.gateway.routes[8].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[8].predicates=Path=/user/**
spring.cloud.gateway.routes[8].filters=StripPrefix=1


# NSE service
spring.cloud.gateway.routes[9].id=nse-service
spring.cloud.gateway.routes[9].uri=lb://NSE-SERVICE
spring.cloud.gateway.routes[9].predicates=Path=/nse/**
spring.cloud.gateway.routes[9].filters=StripPrefix=1

# AMFI service
spring.cloud.gateway.routes[10].id=amfi-service
spring.cloud.gateway.routes[10].uri=lb://AMFI-SERVICE
spring.cloud.gateway.routes[10].predicates=Path=/amfi/**
spring.cloud.gateway.routes[10].filters=StripPrefix=1

# BSE service
spring.cloud.gateway.routes[11].id=bse-service
spring.cloud.gateway.routes[11].uri=lb://BSE-SERVICE
spring.cloud.gateway.routes[11].predicates=Path=/bse/**
spring.cloud.gateway.routes[11].filters=StripPrefix=1

# AUM service
spring.cloud.gateway.routes[12].id=aum-service
spring.cloud.gateway.routes[12].uri=lb://AUM-SERVICE
spring.cloud.gateway.routes[12].predicates=Path=/aum/**
spring.cloud.gateway.routes[12].filters=StripPrefix=1


# BROKERAGE service
spring.cloud.gateway.routes[13].id=brokerage-service
spring.cloud.gateway.routes[13].uri=lb://BROKERAGE-SERVICE
spring.cloud.gateway.routes[13].predicates=Path=/brokerage/**
spring.cloud.gateway.routes[13].filters=StripPrefix=1

# Swagger UI config at gateway
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

springdoc.swagger-ui.urls[2].name=nse-service
springdoc.swagger-ui.urls[2].url=/nse/v3/api-docs

springdoc.swagger-ui.urls[3].name=amfi-service
springdoc.swagger-ui.urls[3].url=/amfi/v3/api-docs

springdoc.swagger-ui.urls[4].name=bse-service
springdoc.swagger-ui.urls[4].url=/bse/v3/api-docs

springdoc.swagger-ui.urls[5].name=aum-service
springdoc.swagger-ui.urls[5].url=/aum/v3/api-docs


springdoc.swagger-ui.urls[6].name=brokerage-service
springdoc.swagger-ui.urls[6].url=/brokerage/v3/api-docs

springdoc.swagger-ui.path=/internal-api-docs