server.port=8080
spring.application.name=user-service

eureka.client.enabled=false

custom.server.url=https://dev-efmicroservices.advisorkhoj.com/user

vendor.logo.url =https://dev-efmicroservices.advisorkhoj.com/nse/images/vendors/

spring.datasource.url=jdbc:mysql://169.38.132.173:3306/easternfin?
spring.datasource.username=efapi_dev
spring.datasource.password=Efapi@96860!$
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.discovery=true
springdoc.swagger-ui.path=/internal-api-docs

jwt.secret-key = OoZT8hVO0IOr7WZuU7beibI4wQ5cByYX!